---
# 1. Preparing the environment and secrets
- import_playbook: copy-env.yml

# 2. Installing Docker and tools (htop, smartmontools, fail2ban)
- import_playbook: prepare-node.yml

# 3. Network security configuration (UFW)
- import_playbook: deploy-firewall.yml

# 4. Main stack deployment (Unbound, Pi-hole, n8n, Mongo, MySQL, Kali, Portainer)
- import_playbook: deploy-sentinel-core.yml

# 5. Proxy
- import_playbook: deploy-nginx-proxy.yml
