apiVersion: 1
datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysqldb:3306
    database: cyber_intelligence
    user: hunter
    uid: PCF4C4661FE7E0A44
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: "${MYSQL_PASSWORD}"
    editable: true